plugins { id 'com.android.application' }
android {
    namespace 'com.john.onesecoff'
    compileSdk 34
    defaultConfig {
        applicationId "com.john.onesecoff"
        minSdk 28
        targetSdk 34
        versionCode 2
        versionName "1.1"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
